_wandb:
    value:
        cli_version: 0.27.2
        e:
            7lcqb3jyc247vw4ka1qgu5bgsfg0nfoh:
                codePath: c:\Users\Mad\OneDrive\Рабочий стол\working\Quicksilver.ipynb
                codePathLocal: Quicksilver.ipynb
                cpu_count: 12
                cpu_count_logical: 16
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "511152664576"
                        used: "407280992256"
                email: oktmadmom@gmail.com
                executable: c:\Users\Mad\anaconda3\python.exe
                gpu: NVIDIA GeForce RTX 3050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Laptop GPU
                      uuid: GPU-280510ee-3ace-01a5-b940-ae834a19bd7b
                host: DESKTOP-2IEP5FK
                memory:
                    total: "16870006784"
                os: Windows-11-10.0.26200-SP0
                program: c:\Users\Mad\OneDrive\Рабочий стол\working\Quicksilver.ipynb
                python: CPython 3.13.5
                root: c:\Users\Mad\OneDrive\Рабочий стол\working
                startedAt: "2026-06-20T12:38:10.304961Z"
                writerId: 7lcqb3jyc247vw4ka1qgu5bgsfg0nfoh
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 75
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 75
            "3":
                - 2
            "4": 3.13.5
            "5": 0.27.2
            "6": 5.12.1
            "8":
                - 1
                - 3
            "12": 0.27.2
            "13": windows-amd64
